### PR TITLE
Added ANSI functionality

### PR DESCRIPTION
**Pull request by abdullah-if**
Added ANSI functionality, present for long time in Windows version. Obsolete and non-standard yet may cover corner cases. Converter from was found [here](https://github.com/hmwoliul/bangla-converter).

### CODE REVIEW

**Comment by abdullah-if** [comment]
Using ANSI for Bangla writing is non-standard and should not be supported. It is the users who should change rather than Avro. I take back my PR.

**Comment by sarim** [comment]
Thank you very much for your contribution. I appreciate you contributing to the repo :)  Unfortunately this PR isn't suitable for the project right now. Current (javascript) version is in feature freeze. New features would be in v2 (golang version). Also this PR includes a library that is clearly a converter for bijoy, which is a proprietary layout. For obvious I can't accept that code into ibus-avro.

**Comment by apandada1** [comment]
> which is a proprietary layout

@sarim  Is it that even the layout is copyrighted and cannot be included in any other software?

**Comment by oritromax** [comment]
@apandada1 Yes :)

**Comment by abdullah-if** [comment]
Quick question, how Avro in Windows implement ANSI ?

**Pull request closed without merging**
